"""
Python port of the Japanese G2P (grapheme-to-phoneme) logic from
src/inference/pipeline/textProcessing.js (_japaneseG2p).

This module is the SINGLE SOURCE OF TRUTH for Japanese lyric → phoneme
conversion on the Python training side. It MUST produce byte-identical
output to the JS inference-side _japaneseG2p, otherwise training and
inference phoneme token structures will diverge (the root cause of the
'watashino → woc(su)shibi' misalignment bug documented in project_memory).

Input: hiragana / katakana / kanji (with <jp> prefix) / romaji letters.
Output: list of bare phoneme strings (e.g. ['k', 'a', 'ts', 'u']).

Usage:
    from train.lora_jp.jp_g2p import japanese_g2p, syllabify_jp
    phonemes = japanese_g2p("かたつむり")  # ['k','a','t','a','ts','u','m','u','r','i']
    syllables = syllabify_jp(phonemes)     # [['k','a'],['t','a'],['ts','u'],['m','u'],['r','i']]
"""

import re
from typing import List

# ---------------------------------------------------------------------------
# Hiragana → phoneme mapping (exact copy of JP_HIRAGANA_MAP in textProcessing.js)
# ---------------------------------------------------------------------------
JP_HIRAGANA_MAP = {
    'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
    'か': 'k a', 'き': 'k i', 'く': 'k u', 'け': 'k e', 'こ': 'k o',
    'さ': 's a', 'し': 'sh i', 'す': 's u', 'せ': 's e', 'そ': 's o',
    'た': 't a', 'ち': 'ch i', 'つ': 'ts u', 'て': 't e', 'と': 't o',
    'な': 'n a', 'に': 'ny i', 'ぬ': 'n u', 'ね': 'n e', 'の': 'n o',
    'は': 'h a', 'ひ': 'hy i', 'ふ': 'f u', 'へ': 'h e', 'ほ': 'h o',
    'ま': 'm a', 'み': 'my i', 'む': 'm u', 'め': 'm e', 'も': 'm o',
    'や': 'y a', 'ゆ': 'y u', 'よ': 'y o',
    'ら': 'r a', 'り': 'ry i', 'る': 'r u', 'れ': 'r e', 'ろ': 'r o',
    'わ': 'w a', 'を': 'o', 'ん': 'n',
    'が': 'g a', 'ぎ': 'gy i', 'ぐ': 'g u', 'げ': 'g e', 'ご': 'g o',
    'ざ': 'z a', 'じ': 'j i', 'ず': 'z u', 'ぜ': 'z e', 'ぞ': 'z o',
    'だ': 'd a', 'ぢ': 'j i', 'づ': 'z u', 'で': 'd e', 'ど': 'd o',
    'ば': 'b a', 'び': 'by i', 'ぶ': 'b u', 'べ': 'b e', 'ぼ': 'b o',
    'ぱ': 'p a', 'ぴ': 'py i', 'ぷ': 'p u', 'ぺ': 'p e', 'ぽ': 'p o',
    'きゃ': 'ky a', 'きゅ': 'ky u', 'きょ': 'ky o',
    'しゃ': 'sh a', 'しゅ': 'sh u', 'しょ': 'sh o',
    'ちゃ': 'ch a', 'ちゅ': 'ch u', 'ちょ': 'ch o',
    'にゃ': 'ny a', 'にゅ': 'ny u', 'にょ': 'ny o',
    'ひゃ': 'hy a', 'ひゅ': 'hy u', 'ひょ': 'hy o',
    'みゃ': 'my a', 'みゅ': 'my u', 'みょ': 'my o',
    'りゃ': 'ry a', 'りゅ': 'ry u', 'りょ': 'ry o',
    'ぎゃ': 'gy a', 'ぎゅ': 'gy u', 'ぎょ': 'gy o',
    'じゃ': 'j a', 'じゅ': 'j u', 'じょ': 'j o',
    'びゃ': 'by a', 'びゅ': 'by u', 'びょ': 'by o',
    'ぴゃ': 'py a', 'ぴゅ': 'py u', 'ぴょ': 'py o',
    'てゃ': 't a', 'てゅ': 't u', 'てょ': 't o',
    'でゃ': 'd a', 'でゅ': 'd u', 'でょ': 'd o',
    'っ': 'cl',
}

# Katakana map auto-generated by shifting each hiragana char code by +0x60
# (same logic as textProcessing.js lines 38-42).
JP_KATAKANA_MAP = {}
for _hira, _ph in JP_HIRAGANA_MAP.items():
    _kata = chr(ord(_hira[0]) + 0x60) + _hira[1:]
    JP_KATAKANA_MAP[_kata] = _ph

# ---------------------------------------------------------------------------
# Kanji dictionary (exact copy of JP_KANJI_DICT in textProcessing.js)
# ---------------------------------------------------------------------------
JP_KANJI_DICT = {
    '愛': 'a i', '雨': 'a m e', '空': 's o r a', '花': 'h a n a',
    '風': 'k a z e', '月': 'ts u k i', '星': 'h o sh i', '雪': 'y u k i',
    '海': 'u m i', '山': 'y a m a', '川': 'k a w a', '森': 'm o r i',
    '光': 'h i k a r i', '音': 'o t o', '声': 'k o e', '梦': 'y u m e',
    '心': 'k o k o r o', '恋': 'k o i', '涙': 'n a m i d a',
    '歌': 'u t a', '飛': 't o b u', '歩': 'a r u k u',
    '走': 'h a sh i r u', '泳': 'o y o g u', '読': 'y o m u',
    '食': 't a b e r u', '飲': 'n o m u', '見': 'm i r u', '聞': 'k i k u',
    '帰': 'k a e r u', '行': 'i k u', '来': 'k u r u', '立': 't a ts u',
    '入': 'h a i r u', '出': 'd e r u', '上': 'u e', '下': 's h i t a',
    '大': 'o o', '小': 'ch i i s a', '長': 'n a g a i', '強': 'ts u y o i',
    '春': 'h a r u', '夏': 'n a ts u', '秋': 'a k i', '冬': 'f u y u',
    '朝': 'a s a', '昼': 'h i r u', '夜': 'y o r u',
    '今': 'i m a', '私': 'w a t a sh i', '君': 'k i m i',
    '一': 'i ch i', '二': 'n i', '三': 's a n', '四': 'y o n',
    '五': 'g o', '六': 'r o k u', '七': 'n a n a', '八': 'h a ch i',
    '九': 'ky u', '十': 'j u',
}

# Regex patterns (mirror textProcessing.js)
_JP_KANA_RE = re.compile(r'[ぁ-ゟァ-ヿ]')          # _isJapanese
_JP_KANJI_RE = re.compile(r'[一-鿿]')              # kanji range in _japaneseG2p
_LATIN_RE = re.compile(r'[a-zA-Z]')

# Consonant set used by prepare_dataset.py (must match PHONEME_MAP consonants)
# Used for syllabification downstream.
JP_CONSONANTS = {
    'k', 's', 't', 'n', 'h', 'm', 'r', 'w', 'y', 'g', 'z', 'd', 'b', 'p',
    'f', 'j', 'ch', 'sh', 'ts', 'ky', 'gy', 'ny', 'hy', 'my', 'ry', 'py', 'by', 'cl',
}
JP_VOWELS = {'a', 'i', 'u', 'e', 'o'}


def is_japanese(text: str) -> bool:
    """Return True if text contains hiragana or katakana (NOT kanji).

    Mirrors _isJapanese in textProcessing.js (line 257-260).
    Kanji is deliberately excluded because it overlaps with Chinese.
    """
    return bool(_JP_KANA_RE.search(text))


def japanese_g2p(text: str) -> List[str]:
    """Convert Japanese text to a flat list of phoneme strings.

    EXACT Python port of _japaneseG2p in textProcessing.js (lines 262-306).
    Output is a list of bare phonemes (no jp_ prefix), e.g. ['k','a','ts','u'].

    Rules (in order, matching JS):
      1. Skip 'ー' (long vowel) and '〜' (wave dash).
      2. Try 2-char combo (yoon like きゃ) in hiragana/katakana maps first.
      3. Try single char in hiragana/katakana maps.
      4. Kanji: try 4→2 char compounds in JP_KANJI_DICT, then single char,
         else emit 'pau'.
      5. Latin letters [a-zA-Z]: emit lowercase single char.
      6. Everything else: skip.
    """
    result: List[str] = []
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]

        # Rule 1: skip long-vowel mark and wave dash
        if ch == 'ー' or ch == '〜':
            i += 1
            continue

        # Rule 2: 2-char combo (yoon)
        if i + 1 < n:
            combo = ch + text[i + 1]
            ph = JP_HIRAGANA_MAP.get(combo) or JP_KATAKANA_MAP.get(combo)
            if ph is not None:
                result.extend(ph.split(' '))
                i += 2
                continue

        # Rule 3: single char
        ph = JP_HIRAGANA_MAP.get(ch) or JP_KATAKANA_MAP.get(ch)
        if ph is not None:
            result.extend(ph.split(' '))
            i += 1
            continue

        # Rule 4: kanji
        if _JP_KANJI_RE.match(ch):
            found = False
            # Try compounds of length 4 down to 2
            max_len = min(4, n - i)
            for length in range(max_len, 1, -1):
                compound = text[i:i + length]
                if compound in JP_KANJI_DICT:
                    result.extend(JP_KANJI_DICT[compound].split(' '))
                    i += length
                    found = True
                    break
            if not found:
                kanji_ph = JP_KANJI_DICT.get(ch)
                if kanji_ph is not None:
                    result.extend(kanji_ph.split(' '))
                else:
                    result.append('pau')
                i += 1
            continue

        # Rule 5: Latin letter
        if _LATIN_RE.match(ch):
            result.append(ch.lower())
            i += 1
            continue

        # Rule 6: skip everything else
        i += 1

    return result


def syllabify_jp(phonemes: List[str]) -> List[List[str]]:
    """Group a flat phoneme list into Japanese syllable units.

    A syllable = optional consonant (or consonant cluster) + one vowel.
    The sokuon 'cl' is a standalone syllable. 'pau' and 'n' (moraic nasal)
    are standalone syllables.

    This mirrors the syllable-splitting logic in prepare_dataset.py's
    split_lab_into_syllables(), but operates on G2P output instead of lab
    segments. The result is used to build the merged 'jp_t-a' format that
    DataProcessor.preprocess() expects (one syllable per MIDI note).

    Examples:
        ['k','a','t','a','ts','u'] -> [['k','a'],['t','a'],['ts','u']]
        ['d','e','n','d','e','n']  -> [['d','e'],['n'],['d','e'],['n']]
        ['ts','u','n','o']         -> [['ts','u'],['n'],['n','o']]
    """
    syllables: List[List[str]] = []
    i = 0
    n = len(phonemes)
    while i < n:
        ph = phonemes[i]

        # Sokuon (促音) → standalone
        if ph == 'cl':
            syllables.append([ph])
            i += 1
            continue

        # Moraic nasal ん → standalone syllable
        if ph == 'n':
            # Check if followed by a vowel (shouldn't happen in valid JP G2P,
            # but handle gracefully) — if so, treat as consonant.
            if i + 1 < n and phonemes[i + 1] in JP_VOWELS:
                pass  # fall through to consonant handling
            else:
                syllables.append([ph])
                i += 1
                continue

        # 'pau' → standalone
        if ph == 'pau':
            syllables.append([ph])
            i += 1
            continue

        # Vowel-only syllable
        if ph in JP_VOWELS:
            syllables.append([ph])
            i += 1
            continue

        # Consonant: collect cluster + following vowel if present
        if ph in JP_CONSONANTS:
            consonant = ph
            if i + 1 < n and phonemes[i + 1] in JP_VOWELS:
                vowel = phonemes[i + 1]
                syllables.append([consonant, vowel])
                i += 2
            else:
                # Consonant without following vowel (rare) — standalone
                syllables.append([consonant])
                i += 1
            continue

        # Unknown phoneme — standalone (shouldn't happen with valid G2P output)
        syllables.append([ph])
        i += 1

    return syllables


def lyrics_to_jp_tokens(lyrics: str) -> List[str]:
    """Full pipeline: lyrics text → merged jp_* tokens (e.g. 'jp_t-a').

    This produces the exact token format that prepare_dataset.py emits and
    that DataProcessor.preprocess() consumes. Each token corresponds to one
    syllable (one MIDI note at inference time).

    Example:
        "かたつむり" → ['jp_k-a','jp_t-a','jp_ts-u','jp_m-u','jp_r-i']
    """
    phonemes = japanese_g2p(lyrics)
    syllables = syllabify_jp(phonemes)
    tokens = []
    for syl in syllables:
        if syl == ['pau']:
            tokens.append('<SP>')
            continue
        if syl == ['cl']:
            tokens.append('jp_cl')
            continue
        # Build 'jp_' + consonant + '-' + vowel (or just 'jp_vowel' for V-only)
        parts = ['jp_' + p for p in syl]
        # Merge into single token: 'jp_t-a' style
        merged = 'jp_' + '-'.join(p[3:] for p in parts)
        tokens.append(merged)
    return tokens


# ---------------------------------------------------------------------------
# Self-test: verify parity with the JS implementation
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    # Test cases: (input, expected phoneme list from JS _japaneseG2p)
    # NOTE: the JS map uses palatalized consonants for the "i" row:
    #   り→'ry i', に→'ny i', ひ→'hy i', み→'my i', etc.
    test_cases = [
        ("かたつむり", ['k','a','t','a','ts','u','m','u','ry','i']),
        ("さくら",     ['s','a','k','u','r','a']),
        ("でんでんむし", ['d','e','n','d','e','n','m','u','sh','i']),
        ("おまえの",   ['o','m','a','e','n','o']),
        ("あたまは",   ['a','t','a','m','a','h','a']),
        ("どこにある", ['d','o','k','o','ny','i','a','r','u']),
        ("つの",       ['ts','u','n','o']),
        ("だせ",       ['d','a','s','e']),
        ("やり",       ['y','a','ry','i']),
        ("めだまは",   ['m','e','d','a','m','a','h','a']),
        ("きゃ",       ['ky','a']),
        ("しゃ",       ['sh','a']),
        ("ちゃ",       ['ch','a']),
        ("っ",         ['cl']),
        ("ん",         ['n']),
        ("を",         ['o']),
        ("サクラ",     ['s','a','k','u','r','a']),  # katakana
        ("ー",         []),                          # long vowel mark skipped
    ]

    print("=== G2P parity test (Python vs JS) ===")
    all_passed = True
    for text, expected in test_cases:
        result = japanese_g2p(text)
        ok = result == expected
        status = 'PASS' if ok else 'FAIL'
        if not ok:
            all_passed = False
        print(f"  [{status}] '{text}' -> {result}" + ("" if ok else f"  (expected {expected})"))

    print("\n=== Syllabification test ===")
    syllable_cases = [
        # り→'ry i' so syllable is ['ry','i']; の→'n o' so ['n','o'] (no standalone ん)
        ("かたつむり", [['k','a'],['t','a'],['ts','u'],['m','u'],['ry','i']]),
        ("でんでんむし", [['d','e'],['n'],['d','e'],['n'],['m','u'],['sh','i']]),
        ("つの", [['ts','u'],['n','o']]),
    ]
    for text, expected in syllable_cases:
        phonemes = japanese_g2p(text)
        result = syllabify_jp(phonemes)
        ok = result == expected
        status = 'PASS' if ok else 'FAIL'
        if not ok:
            all_passed = False
        print(f"  [{status}] '{text}' -> {result}" + ("" if ok else f"  (expected {expected})"))

    print("\n=== Token format test (jp_t-a style) ===")
    token_cases = [
        ("かたつむり", ['jp_k-a','jp_t-a','jp_ts-u','jp_m-u','jp_ry-i']),
        ("でんでんむし", ['jp_d-e','jp_n','jp_d-e','jp_n','jp_m-u','jp_sh-i']),
    ]
    for text, expected in token_cases:
        result = lyrics_to_jp_tokens(text)
        ok = result == expected
        status = 'PASS' if ok else 'FAIL'
        if not ok:
            all_passed = False
        print(f"  [{status}] '{text}' -> {result}" + ("" if ok else f"  (expected {expected})"))

    print(f"\n{'ALL TESTS PASSED' if all_passed else 'SOME TESTS FAILED'}")
